### ISSUE TITLE
Implement API route to return a specific Skill

### ISSUE THREAD

**Issue by MLHProgram** [MLH-Fellowship/orientation-project-python-24.SUM.A#13]
On the `/resume/skill` route, you should

- [ ] Return a specific Skill when a GET request is made with an index as an input. The Skill should be in a JSON format.

**Comment by winstxnhdw** [comment]
I'll do this.

**Comment by IvanKolchanov** [comment]
Closed with PR #29 
@Pradyuman7 (I don't have the rights to close the issue myself)
