### ISSUE TITLE
Failing tests due to not returning missing fields error

### ISSUE THREAD

**Issue by Pradyuman7** [MLH-Fellowship/orientation-project-python-24.SUM.A#37]
By the way, we have 2 pytests failing because the change to POST /resume/education, which doesn't return missing fields now, causes the tests to fail :0. Just noticed that when posting a PR and wanted to say 👍

_Originally posted by @IvanKolchanov in https://github.com/MLH-Fellowship/orientation-project-python-24.SUM.A/issues/27#issuecomment-2131403474_

**Comment by andyjianzhou** [comment]
I can take on this :P
